import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useSelector } from 'react-redux'
import { RootState } from '../redux/store'
import StartScreen from '../components/StartScreen'
import GameScreen from '../components/GameScreen'

const Home: NextPage = () => {
  const gameStatus = useSelector(
    (state: RootState) => state.gameConfig.config.gameStatus
  )
  return (
    <div className='flex flex-col min-h-screen items-center justify-center'>
      <Head>
        <title>Game</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {gameStatus === 'idle' ? <StartScreen /> : <GameScreen />}
    </div>
  )
}

export default Home
